[workspace]
resolver = "2"  # 使用2021版本的Rust解析器
members = ["crates/*"] # 该工作空间的所有crate
default-members = ["crates/app"] # 默认情况下，只有此会被构建或运行

[workspace.dependencies]
gpui = { git = "https://github.com/zed-industries/zed" }
ui = { path = "crates/ui" }
